{{- if .Values.rollout.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
{{- else if .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
{{- end }}
metadata:
  name: {{ .Values.name }}-{{ .Values.environment }}
  namespace: {{ .Values.environment }}
  labels:
    {{- include "qrify-base.labels" . | nindent 4 }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qrify-base.selectorLabels" . | nindent 6 }}
  {{- if .Values.rollout.enabled }}
  strategy:
    blueGreen:
      activeService: {{ .Values.rollout.activeService | quote }}
      previewService: {{ .Values.rollout.previewService | quote }}
      autoPromotionEnabled: {{ .Values.rollout.autoPromotionEnabled | default true }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "qrify-base.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ include "qrify.ecrRegistry" . }}/{{ .Values.name }}-{{ .Values.environment }}:{{ .Values.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            {{- range .Values.envSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
