{{- if .Values.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.environment }}
  namespace: {{ .Values.environment }}
  labels:
  {{- include "qrify-base.labels" . | nindent 2 }}
  {{- with .Values.labels }}
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "qrify-base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | default dict | nindent 8 }}
    labels:
    {{- include "qrify-base.labels" . | nindent 2 }}
    {{- with .Values.podLabels }}
    {{- range $key, $value := . }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ include "qrify.ecrRegistry" . }}/{{ .Values.name }}-{{ .Values.environment }}:{{ .Values.imageTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          envFrom:
            {{- range .Values.envSecrets }}
            - secretRef:
                name: {{ . }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
{{- end }}
