{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}-{{ .Values.environment }}-monitor
  namespace: {{ .Values.environment }}
  labels:
    release: prometheus 
    {{- include "qrify-base.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "qrify-base.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Values.environment }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
{{- end }}
