{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.environment }}
  labels:
    {{- include "qrify-base.labels" . | nindent 4 }}
    {{ .Values.labels | default dict | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.service.port }}
  selector:
    {{- include "qrify-base.selectorLabels" . | nindent 4 }}
{{- end }}