# App configuration
name: "" # Name of the application 
environment: "" # Environment (e.g. dev, prod)
imageTag: "" 
deployment: true # Set to false to disable deployment
replicaCount: 2 # Number of replicas

image:
  repository: ""  # Optional override for the image repository
  pullPolicy: IfNotPresent # Image pull policy (e.g. Always, IfNotPresent, Never)

# Environment variables
env: [] 
# Example:
# - name: NEXT_PUBLIC_API_BASE_URL
#   value: "https://api.qrify.com"

# Service configuration
service:
  type: ClusterIP # Service type (e.g. ClusterIP, NodePort, LoadBalancer)
  port: 80 # Service port

# Ingress configuration
ingress:
  enabled: false
  className: ""  # e.g. "nginx"
  annotations: {}
  # Example:
  #   kubernetes.io/ingress.class: "nginx"
  hosts: []
  # Example:
  #   - host: qrify-web.yourdomain.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  tls: []
  # Example:
  #   - secretName: qrify-web-tls
  #     hosts:
  #       - qrify-web.yourdomain.com

# Kubernetes resource limits
resources: {} 
# Example:
# limits:
#   cpu: "100m"
#   memory: "128Mi"
# requests:
#   cpu: "100m"
#   memory: "128Mi"


# Probes (optional) 
livenessProbe: {}
readinessProbe: {}
